### ISSUE TITLE
API request limit

### ISSUE THREAD

**Issue by pi-yush** [fiatjaf/lnchannels#2]
Hi,

I have been trying to use API calls to fetch the channels and policy information.
However, currently I am only able to retrieve the latest 100000 data points.

Is there a way to obtain all the historic data in your database at once using the API?
Or can I retrieve all data using multiple API request? If so, can you guide about the format of such API request?

**Comment by fiatjaf** [comment]
The recommended way is to download the full Postgres database through the link provided at the top: https://ln.bigsun.xyz/lnchannels.dump

There is also a way to get just the channels data as CSV: https://ln.bigsun.xyz/channels.csv

Please do that and do not send a ton of API requests.
