### ISSUE TITLE
How to retrieve more information about nodes and channels?

### ISSUE THREAD

**Issue by theova** [fiatjaf/lnchannels#3]
Hi,

Thank you for this amazing website and the fantastic API!

I wonder, is there a way to obtain more information about nodes and channels?
For example, in your data you do not include the IP/onion addresses of the nodes. Or similar, it would be nice to obtain the transaction fees for a channel.

Is there a way to obtain this data for all nodes/channels using your website?

Thanks a lot!

**Comment by fiatjaf** [comment]
Download the PostgreSQL database dump.

**Comment by theova** [comment]
> Download the PostgreSQL database dump.

Alright thanks!
